create table course (id bigint not null auto_increment, img_gray_uri varchar(255), img_uri varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table offer (course_id bigint, end_moment TIMESTAMP WITHOUT TIME ZONE null, id bigint not null auto_increment, start_moment TIMESTAMP WITHOUT TIME ZONE null, edition varchar(255), primary key (id)) engine=InnoDB;
create table perfil (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table usuario (atualizado_em TIMESTAMP WITHOUT TIME ZONE null, criado_em TIMESTAMP WITHOUT TIME ZONE null, id bigint not null auto_increment, email varchar(255), nome varchar(255), senha varchar(255), telefone varchar(255), primary key (id)) engine=InnoDB;
create table usuario_perfil (id_perfil bigint not null, id_usuario bigint not null, primary key (id_perfil, id_usuario)) engine=InnoDB;
alter table offer add constraint FK1q17i2dp3jm59xlih21imsakd foreign key (course_id) references course (id);
alter table usuario_perfil add constraint FK3cxlmf5q4y8mllkos025n9px8 foreign key (id_perfil) references perfil (id);
alter table usuario_perfil add constraint FK2qe6tjawyl6ojl32uhbwllldh foreign key (id_usuario) references usuario (id);
INSERT INTO tb_user (name, email, password) VALUES ('Alex Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Maria Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_role (authority) VALUES ('ROLE_STUDENT');
INSERT INTO tb_role (authority) VALUES ('ROLE_INSTRUCTOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 3);
create table course (id bigint not null auto_increment, img_gray_uri varchar(255), img_uri varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table offer (course_id bigint, end_moment TIMESTAMP WITHOUT TIME ZONE null, id bigint not null auto_increment, start_moment TIMESTAMP WITHOUT TIME ZONE null, edition varchar(255), primary key (id)) engine=InnoDB;
create table perfil (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table usuario (atualizado_em TIMESTAMP WITHOUT TIME ZONE null, criado_em TIMESTAMP WITHOUT TIME ZONE null, id bigint not null auto_increment, email varchar(255), nome varchar(255), senha varchar(255), telefone varchar(255), primary key (id)) engine=InnoDB;
create table usuario_perfil (id_perfil bigint not null, id_usuario bigint not null, primary key (id_perfil, id_usuario)) engine=InnoDB;
alter table offer add constraint FK1q17i2dp3jm59xlih21imsakd foreign key (course_id) references course (id);
alter table usuario_perfil add constraint FK3cxlmf5q4y8mllkos025n9px8 foreign key (id_perfil) references perfil (id);
alter table usuario_perfil add constraint FK2qe6tjawyl6ojl32uhbwllldh foreign key (id_usuario) references usuario (id);
INSERT INTO tb_user (name, email, password) VALUES ('Alex Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Maria Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_role (authority) VALUES ('ROLE_STUDENT');
INSERT INTO tb_role (authority) VALUES ('ROLE_INSTRUCTOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 3);
